version: '2'
services:
    meatshopservices-app:
        image: meatshopservices
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://meatshopservices-mysql:3306/meatshopservices?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    meatshopservices-mysql:
        extends:
            file: mysql.yml
            service: meatshopservices-mysql
